create table if not exists public.ticket_notifications (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  notification_type text not null check (notification_type in ('rsvp_prompt', 'reminder_24h')),
  email_message_id text null,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (ticket_id, notification_type)
);

create index if not exists ticket_notifications_type_sent_at_idx
  on public.ticket_notifications (notification_type, sent_at desc);